### ISSUE TITLE
Could not convert string to float

### ISSUE THREAD

**Issue by brandonleon** [gtdiehl/eagle200_reader#7]
I'be been getting errors with this library when trying to query my Eagle 200, I suspect the API has changed causing this issue I was posting in the Home Assistant Subreddit for help on this issue: https://www.reddit.com/r/homeassistant/comments/p05jdd/rainforest_eagle_integration_not_working/h85lqmk/

The user I was asking for help is seeing the Unit's provided as a value by itself, and the library works for them.
```xml
<Variable>
  <Name>zigbee:InstantaneousDemand</Name>
    <Value>0.720000</Value>
    <Units>kW</Units>
  <Description>Instantaneous Demand</Description>
</Variable>
```

But the [docs (page 12)](https://rainforestautomation.com/wp-content/uploads/2017/02/EAGLE-200-Local-API-Manual-v1.0.pdf) and my Eagle are returning the Unit inline with the value.

```xml
<Variable>
  <Name>zigbee:InstantaneousDemand</Name>
  <Value>4294963.584000 kW</Value>
</Variable>
```

When calling eagle200_reader.py directly and passing my IP, Cloud_Id, and install_code I get the following errors:

```bash
brandon.leon ❯ python eagle200_reader.py $ip $cloud_id $install_code      
Traceback (most recent call last):
  File "/Users/brandon.leon/.virtualenvs/Eagle200-RpHpq0KU/lib/python3.9/site-packages/eagle200_reader/eagle200_reader.py", line 224, in <module>
    testreader = EagleReader(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/Users/brandon.leon/.virtualenvs/Eagle200-RpHpq0KU/lib/python3.9/site-packages/eagle200_reader/eagle200_reader.py", line 28, in __init__
    self._call_api()
  File "/Users/brandon.leon/.virtualenvs/Eagle200-RpHpq0KU/lib/python3.9/site-packages/eagle200_reader/eagle200_reader.py", line 55, in _call_api
    self._summation_total(self._create_attributes(response))
  File "/Users/brandon.leon/.virtualenvs/Eagle200-RpHpq0KU/lib/python3.9/site-packages/eagle200_reader/eagle200_reader.py", line 209, in _summation_total
    self.summation_total_value = (float(self.summation_delivered_value) - float(self.summation_received_value))
ValueError: could not convert string to float: '25.991000 kWh'
```

**Comment by mririgoyen** [comment]
+1. The API has obviously changed and a quick fix to this would be much appreciated.

**Comment by nicholashead** [comment]
For what it's worth, I bought my EAGLE-200 a week or so ago, and it's spitting out the separated syntax (first example above). The software version shows 3.15.4.475 - I am not sure if there's a way to query that via their local API. Otherwise this library could query for v2 or v3 and act appropriately. I would maybe reach out to Rainforest and see if they can push an update to your EAGLE-200? @brandonleon 

Otherwise we'll have to wait for someone with Python experience to update this library. I can give it a whirl (I'm a software engineer) but I have never worked with Python and I'll have to learn.

**Comment by nicholashead** [comment]
What version do your Eagle gateways show, when you log into their cloud portal?

**Comment by mririgoyen** [comment]
I am on `3.15.4.475`.

**Comment by brandonleon** [comment]
I just submitted a ticket to Rainforest to see if they can push an update according to the web portal, I'm running version 2.14.4.

**Comment by nicholashead** [comment]
@goyney you're on 3.15.4.475 and experiencing the issue?

**Comment by BillyFKidney** [comment]
This issue appears to be fixed with core-2021.8.6

Home Assistant
<img width="369" alt="image" src="https://user-images.githubusercontent.com/65253277/129052725-facb87d8-bd95-40f9-badd-314dbb34b95f.png">

Rainforest Cloud Web
![image](https://user-images.githubusercontent.com/65253277/129052862-71f6aab2-dc4f-4f7c-b86d-962d77e90ae1.png)

API Test
![image](https://user-images.githubusercontent.com/65253277/129053419-1e6b3992-01b9-4797-8a76-cc2cadf25562.png)

**Comment by brandonleon** [comment]
This seems limited to my unit. It appears I'm still running 2.x and Rainforest themselves are not confidant they can push an update to it remotely. I'm going to be sending them my device shortly to attempt an update on their bench. Since this is an isolated incident, I think we can close this issue.

**Comment by gtdiehl** [comment]
Closing issue. Home Assistant is no longer using the ```eagle200_reader``` library
